replicaCount: 1
image:
  repository: akushwah/acctmgmt-service
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  port: 8092
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: acctmgmt-service.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
kafka:
  bootstrapServers: "192.168.0.104:9092"
