apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "notification-service.name" . }}
  labels:
    app: {{ include "notification-service.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "notification-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "notification-service.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8093
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.kafka.bootstrapServers | quote }}
            - name: MAILHOG_HOST
              value: {{ .Values.mailhog.host | quote }}
            - name: MAILHOG_PORT
              value: {{ .Values.mailhog.port | quote }}