{{/*apiVersion: networking.k8s.io/v1*/}}
{{/*kind: Ingress*/}}
{{/*metadata:*/}}
{{/*  name: alb-notification-service-ingress*/}}
{{/*spec:*/}}
{{/*  ingressClassName: alb*/}}
{{/*  rules:*/}}
{{/*    - host: notifications.local*/}}
{{/*      http:*/}}
{{/*        paths:*/}}
{{/*          - path: /notifications*/}}
{{/*            pathType: Prefix*/}}
{{/*            backend:*/}}
{{/*              service:*/}}
{{/*                name: notification-service*/}}
{{/*                port:*/}}
{{/*                  number: 8090*/}}