apiVersion: v1
kind: Service
metadata:
  name: {{ include "notification-service.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8093
      protocol: TCP
      name: http
  selector:
    app: {{ include "notification-service.name" . }}

