apiVersion: apps/v1
kind: Deployment
metadata:
  name: acctmgmt-service
  labels:
    app: acctmgmt-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: acctmgmt-service
  template:
    metadata:
      labels:
        app: acctmgmt-service
    spec:
      containers:
        - name: acctmgmt-service
          image: "akushwah/acctmgmt-service:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP