apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alb-acctmgmt-service-ingress
spec:
  ingressClassName: alb
  rules:
    - host: accounts.local
      http:
        paths:
          - path: /accounts
            pathType: Prefix
            backend:
              service:
                name: acctmgmt-service
                port:
                  number: 8092