apiVersion: v1
kind: Service
metadata:
  name: acctmgmt-service
spec:
  type: LoadBalancer  # This exposes it externally (via minikube tunnel)
  selector:
    app: acctmgmt-service
  ports:
    - protocol: TCP
      port: 8092
      targetPort: 8092
