apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-service
  labels:
    app: alert-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: alert-service
  template:
    metadata:
      labels:
        app: alert-service
    spec:
      containers:
        - name: alert-service
          image: "akushwah/alert-service:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP