{{/*apiVersion: networking.k8s.io/v1*/}}
{{/*kind: Ingress*/}}
{{/*metadata:*/}}
{{/*  name: alb-alert-service-ingress*/}}
{{/*spec:*/}}
{{/*  ingressClassName: alb*/}}
{{/*  rules:*/}}
{{/*    - host: alerts.local*/}}
{{/*      http:*/}}
{{/*        paths:*/}}
{{/*          - path: /alerts*/}}
{{/*            pathType: Prefix*/}}
{{/*            backend:*/}}
{{/*              service:*/}}
{{/*                name: alert-service*/}}
{{/*                port:*/}}
{{/*                  number: 8091*/}}