apiVersion: v1
kind: Service
metadata:
  name: {{ include "alert-service.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8091
      protocol: TCP
      name: http
  selector:
    app: {{ include "alert-service.name" . }}

