apiVersion: v1
kind: Service
metadata:
  name: alert-service
  labels:
    app: alert-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8091
      targetPort: 8091
      protocol: TCP
  selector:
    app: alert-service