replicaCount: 1
image:
  repository: akushwah/notification-service
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  port: 8093
kafka:
  bootstrapServers: "192.168.0.104:9092"
mailhog:
  host: "192.168.0.104"
  port: "1025"